/** Human readable descriptions for the command groups (OpenAPI tags carry no descriptions). */
export const GROUP_DESCRIPTIONS: Readonly<Record<string, string>> = {
  Authorization: 'Manage authorizations (permissions of users and groups on resources)',
  Batch: 'Inspect, suspend and delete running batches',
  Condition: 'Evaluate conditional start events',
  'Decision Definition': 'Query deployed DMN decisions, fetch their XML and evaluate them',
  'Decision Requirements Definition': 'Query deployed decision requirements graphs (DRD)',
  Deployment: 'Deploy BPMN/DMN/form resources, list and delete deployments',
  Engine: 'List the process engines served by this REST API',
  'Event Subscription': 'Query message, signal and conditional event subscriptions',
  Execution: 'Query executions, signal them and manage execution variables',
  'External Task': 'Fetch, lock, complete and fail external tasks',
  Filter: 'Manage saved task filters and execute them',
  Group: 'Manage identity groups and their members',
  'Historic Activity Instance': 'Query the history of executed activities',
  'Historic Batch': 'Query and clean up finished batches',
  'History Cleanup': 'Trigger and configure history cleanup',
  'Historic Decision Definition': 'Reports on historic decision definitions',
  'Historic Decision Instance': 'Query and delete historic decision evaluations',
  'Historic Decision Requirements Definition': 'Statistics on historic decision requirements',
  'Historic Detail': 'Query historic variable updates and form fields',
  'Historic External Task Log': 'Query the external task log',
  'Historic Identity Link Log': 'Query the history of identity links (assignees, candidates)',
  'Historic Incident': 'Query historic incidents',
  'Historic Job Log': 'Query the job log, including exception stacktraces',
  'Historic Process Definition': 'Reports and statistics on historic process definitions',
  'Historic Process Instance': 'Query, report on and delete finished and running process instances',
  'Historic Task Instance': 'Query historic user tasks and task reports',
  'Historic User Operation Log': 'Query the user operation (audit) log',
  'Historic Variable Instance': 'Query historic process variables',
  Identity: 'Verify users and query identity information',
  Incident: 'Query, resolve and annotate open incidents',
  Job: 'Query, execute, retry and suspend jobs (timers, async continuations)',
  'Job Definition': 'Query job definitions and set their retries, priority and suspension state',
  Message: 'Correlate messages to process instances',
  Metrics: 'Query engine metrics such as activity instances and task workers',
  Migration: 'Generate, validate and execute process instance migration plans',
  Modification: 'Modify multiple process instances synchronously or as a batch',
  'Process Definition': 'Query process definitions, start instances, fetch BPMN XML and statistics',
  'Process Instance':
    'Query, modify, suspend and delete running process instances and their variables',
  'Process Instance Comment': 'Manage comments on process instances',
  'Schema Log': 'Query the database schema log',
  Signal: 'Throw signals',
  Task: 'Query, claim, assign, complete and delegate user tasks',
  'Task Attachment': 'Manage attachments of user tasks',
  'Task Comment': 'Manage comments on user tasks',
  'Task Identity Link': 'Manage candidate users and groups of user tasks',
  'Task Local Variable': 'Manage task local variables',
  'Task Variable': 'Manage variables visible from a user task',
  Telemetry: 'Read and configure telemetry',
  Tenant: 'Manage tenants and their members',
  User: 'Manage users, profiles and credentials',
  'Variable Instance': 'Query runtime variables across process instances',
  Version: 'Show the REST API version',
};
