/**
 * Explicit command names where the generic naming rule produces awkward or inconsistent results,
 * keyed by operationId. The kebab-cased operationId always stays available as an alias.
 * The builder fails if an override refers to an operationId that no longer exists.
 */
export const NAME_OVERRIDES: Readonly<Record<string, string>> = {
  // list / count / get consistency for resources whose operationIds do not follow the pattern
  queryAuthorizations: 'list',
  getAuthorizationCount: 'count',
  isUserAuthorized: 'check',
  getFilterList: 'list',
  getFilterCount: 'count',
  getSingleFilter: 'get',
  postExecuteFilterCount: 'post-execute-count',
  postExecuteFilterList: 'post-execute-list',
  postExecuteFilterSingleResult: 'post-execute-single-result',
  getQueryGroups: 'list',
  postQueryGroups: 'query',
  getGroupCount: 'count',
  queryGroupCount: 'query-count',
  queryTenants: 'list',
  getTenantCount: 'count',
  getUserCount: 'count',
  getProcessEngineNames: 'list',
  getRestAPIVersion: 'get',
  getMetrics: 'sum',
  historicDetail: 'get',
  historicDetailBinary: 'get-binary',
  getHistoricIdentityLinks: 'list',
  getHistoricIdentityLinksCount: 'count',
  queryUserOperationEntries: 'list',
  queryUserOperationCount: 'count',
  // sub resources of tasks
  addAttachment: 'add',
  deleteAttachment: 'delete',
  getAttachment: 'get',
  getAttachmentData: 'get-data',
  getAttachments: 'list',
  createComment: 'create',
  getComment: 'get',
  getComments: 'list',
  deleteTaskComments: 'delete-all',
  deleteProcessInstanceComments: 'delete-all',
  addIdentityLink: 'add',
  deleteIdentityLink: 'delete',
  getIdentityLinks: 'list',
  setBinaryTaskVariable: 'set-binary',
  setBinaryTaskLocalVariable: 'set-binary',
  // redundant resource names inside the operationId; bulk variants get a -bulk suffix
  completeExternalTaskResource: 'complete',
  setExternalTaskResourcePriority: 'set-priority',
  setExternalTaskResourceRetries: 'set-retries',
  setExternalTaskRetries: 'set-retries-bulk',
  setExternalTaskRetriesAsyncOperation: 'set-retries-async',
  setJobRetriesAsyncOperation: 'set-retries-async',
  deliverMessage: 'correlate',
  getRegisteredDeployments: 'get-registered',
  deleteLocalExecutionVariable: 'delete-local-variable',
  getLocalExecutionVariable: 'get-local-variable',
  getLocalExecutionVariableBinary: 'get-local-variable-binary',
  getLocalExecutionVariables: 'get-local-variables',
  modifyLocalExecutionVariables: 'modify-local-variables',
  putLocalExecutionVariable: 'put-local-variable',
  setLocalExecutionVariableBinary: 'set-local-variable-binary',
  getCleanableHistoricBatchesReport: 'get-cleanable-report',
  getCleanableHistoricBatchesReportCount: 'get-cleanable-report-count',
  setRemovalTimeAsyncHistoricBatch: 'set-removal-time-async',
  getCleanableHistoricDecisionInstanceReport: 'get-cleanable-report',
  getCleanableHistoricDecisionInstanceReportCount: 'get-cleanable-report-count',
  setRemovalTimeAsyncHistoricDecisionInstance: 'set-removal-time-async',
  getErrorDetailsHistoricExternalTaskLog: 'get-error-details',
  getStacktraceHistoricJobLog: 'get-stacktrace',
  getCleanableHistoricProcessInstanceReport: 'get-cleanable-report',
  getCleanableHistoricProcessInstanceReportCount: 'get-cleanable-report-count',
  getHistoricActivityStatistics: 'get-activity-statistics',
  deleteHistoricVariableInstancesOfHistoricProcessInstance: 'delete-variable-instances',
  clearAnnotationUserOperationLog: 'clear-annotation',
  setAnnotationUserOperationLog: 'set-annotation',
  setJobPriorityJobDefinition: 'set-job-priority',
  setJobRetriesJobDefinition: 'set-job-retries',
  // bulk vs. single suspension: bulk is `update-suspension-state`, single is `...-by-id`
  updateSuspensionStateBy: 'update-suspension-state',
  updateJobSuspensionState: 'update-suspension-state-by-id',
  updateSuspensionStateJobDefinitions: 'update-suspension-state',
  updateSuspensionStateJobDefinition: 'update-suspension-state-by-id',
  // process and decision definitions
  // starting by key is the everyday case, so it gets the short name
  startProcessInstanceByKey: 'start',
  startProcessInstance: 'start-by-id',
  startProcessInstanceByKeyAndTenantId: 'start-by-key-and-tenant-id',
  getProcessDefinitionBpmn20XmlByKey: 'xml',
  getProcessDefinitionBpmn20Xml: 'xml-by-id',
  getProcessDefinitionBpmn20XmlByKeyAndTenantId: 'xml-by-key-and-tenant-id',
  getDecisionDefinitionDmnXmlByKey: 'xml',
  getDecisionDefinitionDmnXmlById: 'xml-by-id',
  getDecisionDefinitionDmnXmlByKeyAndTenant: 'xml-by-key-and-tenant-id',
  getDecisionRequirementsDefinitionDmnXmlByKey: 'xml',
  getDecisionRequirementsDefinitionDmnXmlById: 'xml-by-id',
  getDecisionRequirementsDefinitionDmnXmlByKeyAndTenantId: 'xml-by-key-and-tenant-id',
  restartProcessInstance: 'restart',
  restartProcessInstanceAsyncOperation: 'restart-async',
  getLatestProcessDefinitionByTenantId: 'get-by-key-and-tenant-id',
  getActivityStatisticsByProcessDefinitionKey: 'get-activity-statistics-by-key',
  getActivityStatisticsByProcessDefinitionKeyAndTenantId:
    'get-activity-statistics-by-key-and-tenant-id',
  updateHistoryTimeToLiveByProcessDefinitionId: 'update-history-time-to-live-by-id',
  updateHistoryTimeToLiveByProcessDefinitionKey: 'update-history-time-to-live-by-key',
  updateHistoryTimeToLiveByProcessDefinitionKeyAndTenantId:
    'update-history-time-to-live-by-key-and-tenant-id',
  evaluateDecisionById: 'evaluate-by-id',
  evaluateDecisionByKey: 'evaluate-by-key',
  evaluateDecisionByKeyAndTenant: 'evaluate-by-key-and-tenant-id',
  getDecisionDefinitionDiagramByKeyAndTenant: 'get-diagram-by-key-and-tenant-id',
  updateHistoryTimeToLiveByDecisionDefinitionId: 'update-history-time-to-live-by-id',
  updateHistoryTimeToLiveByDecisionDefinitionKey: 'update-history-time-to-live-by-key',
  updateHistoryTimeToLiveByDecisionDefinitionKeyAndTenant:
    'update-history-time-to-live-by-key-and-tenant-id',
  // process instances
  correlateMessageAsyncOperation: 'correlate-message-async',
  deleteProcessInstancesAsyncOperation: 'delete-async',
  modifyProcessInstanceAsyncOperation: 'modify-async',
  setVariablesAsyncOperation: 'set-variables-async',
  updateSuspensionStateAsyncOperation: 'update-suspension-state-async',
  setRetriesByProcess: 'set-job-retries',
  setRetriesByProcessHistoricQueryBased: 'set-job-retries-historic-query-based',
  // one scheme across groups: `list` for collections, `get` for one resource by id
  getSchemaLog: 'list',
  getDecisionDefinitionById: 'get',
  getDecisionRequirementsDefinitionById: 'get',
  getDecisionRequirementsDefinitionDiagramById: 'get-diagram',
  // `update-suspension-state` is the bulk variant, `-by-id` the single one (as for jobs)
  updateBatchSuspensionState: 'update-suspension-state-by-id',
};

/**
 * Additional aliases keyed by operationId, so that one verb works across groups: setting a single
 * variable is `set-variable` for process instances, so `set` works for task variables, too.
 */
export const EXTRA_ALIASES: Readonly<Record<string, readonly string[]>> = {
  putTaskVariable: ['set'],
  putTaskLocalVariable: ['set'],
  putLocalExecutionVariable: ['set-local-variable'],
};
