import { describe, expect, it } from 'vitest';
import { execute, fakeRuntime } from '../../../test/support/fake-runtime.js';
import { run } from '../run.js';

async function help(args: readonly string[]): Promise<string> {
  const result = await execute(run, [...args, '--help'], fakeRuntime());
  expect(result.code).toBe(0);
  return result.stdout;
}

/** The complete help of the utility commands (80 columns, not a terminal). */
const HELP: readonly (readonly [string, readonly string[]])[] = [
  [
    'config',
    [
      'Usage: operate config [options] [command]',
      '',
      'Manage the config file and its profiles. The file is written with mode 0600;',
      'values are validated before they are stored.',
      '',
      'Options:',
      '  -h, --help                 Display help for command',
      '',
      'Commands:',
      '  path                       Print the location of the config file',
      '  show                       Print the effective configuration and where each',
      '                             value comes from; header values and the password',
      '                             are masked unless --show-secrets. -o only formats',
      '                             this output: the values are what an operation',
      '                             command resolves without it.',
      '  list                       List the profiles',
      '  set <profile>              Create or update a profile; only the given values',
      '                             change. The first profile becomes the default.',
      '                             --output is the output format stored in the',
      '                             profile; -o <format> chooses how the profile is',
      '                             printed. Basic auth: --auth basic --auth-user',
      '                             <name> --auth-password-env <VAR> keeps the password',
      '                             in an environment variable.',
      '  unset <profile> <keys...>  Remove values from a profile',
      '  use <profile>              Make a profile the default',
      '  delete <profile>           Delete a profile',
      '  help [command]             Display help for a command',
    ],
  ],
  [
    'config path',
    [
      'Usage: operate config path [options]',
      '',
      'Print the location of the config file',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config show',
    [
      'Usage: operate config show [options]',
      '',
      'Print the effective configuration and where each value comes from; header values',
      'and the password are masked unless --show-secrets. -o only formats this output:',
      'the values are what an operation command resolves without it.',
      '',
      'Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none or basic; a username alone selects',
      '                         basic (env OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config list',
    [
      'Usage: operate config list [options]',
      '',
      'List the profiles',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config set',
    [
      'Usage: operate config set [options] <profile>',
      '',
      'Create or update a profile; only the given values change. The first profile',
      'becomes the default. --output is the output format stored in the profile; -o',
      '<format> chooses how the profile is printed. Basic auth: --auth basic',
      '--auth-user <name> --auth-password-env <VAR> keeps the password in an',
      'environment variable.',
      '',
      'Arguments:',
      '  profile                    Profile name, e.g. local or prod-eu',
      '',
      'Options:',
      '  --url <url>                REST API root, e.g.',
      '                             http://localhost:8080/engine-rest',
      '  --engine <name>            Named process engine',
      '  --auth <type>              Authentication: none or basic',
      '  --auth-user <name>         Username for Basic auth',
      '  --auth-password-env <VAR>  Name of the environment variable that holds the',
      '                             Basic auth password (recommended)',
      '  --auth-password-stdin      Store the password read from the first line of',
      '                             stdin (plain text in the file; discouraged)',
      '  --output <format>          Output format to store in the profile: json or',
      '                             table',
      '  --timeout <ms>             Request timeout in milliseconds',
      '  -H, --header <header>      Header "Name: value" sent with every request;',
      '                             repeatable',
      '  --read-only                Refuse every operation that is not a read',
      '  --no-read-only             Allow operations that change the engine state',
      '  --default                  Make this the default profile',
      '  -o <format>                Output format of the printed profile: json or table',
      '  --config <path>            Config file location (env OPERATE_CONFIG)',
      '  -h, --help                 Display help for command',
    ],
  ],
  [
    'config unset',
    [
      'Usage: operate config unset [options] <profile> <keys...>',
      '',
      'Remove values from a profile',
      '',
      'Arguments:',
      '  profile                Profile name',
      '  keys                   Keys to remove: url, engine, auth, output, timeout,',
      '                         headers, readOnly',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config use',
    [
      'Usage: operate config use [options] <profile>',
      '',
      'Make a profile the default',
      '',
      'Arguments:',
      '  profile                Profile name',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config delete',
    [
      'Usage: operate config delete [options] <profile>',
      '',
      'Delete a profile',
      '',
      'Arguments:',
      '  profile                Profile name',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'commands',
    [
      'Usage: operate commands [group] [options]',
      '',
      'List the API groups, or the commands of a group, a search or an effect.',
      '',
      'Without arguments: every group with its number of commands. With a group,',
      '--search or --effect: the matching commands with method, path, effect and',
      'summary. --search is case-insensitive; each of its words must occur in the',
      'command, its aliases, the operationId, the summary or the path.',
      '',
      'Arguments:',
      '  group                  Group whose commands to list, e.g. process-instance',
      '',
      'Options:',
      '  --search <text>        Commands whose name, alias, operationId, summary or',
      '                         path contain every word of the text',
      '  --effect <effect>      Commands with this effect (choices: "read", "write",',
      '                         "delete", "bulk")',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'describe',
    [
      'Usage: operate describe <group> [command] [options]',
      '',
      'Describe a command: usage, arguments, options, request body schema, responses',
      'and examples.',
      '',
      'Name the command by group and command (process-definition start) or by its',
      'operationId (startProcessInstanceByKey). A group alone lists its commands like',
      '"operate commands <group>". Prints JSON when stdout is not a terminal, readable',
      'text otherwise.',
      '',
      'Arguments:',
      '  group                  Group, e.g. process-definition, or an operationId',
      '  command                Command of the group, e.g. start',
      '',
      'Options:',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'api',
    [
      'Usage: operate api <method> <path> [options]',
      '',
      'Send a raw request to a path relative to the REST API root.',
      '',
      'Adds /engine/<name> when --engine is set and the path does not start with',
      '/engine. Dot segments, repeated and trailing slashes are normalized before the',
      'request is matched and sent. The effect (for --read-only and --yes) is the one',
      'of the catalog operation with the same method and path; other GET, HEAD and',
      'OPTIONS requests are reads, DELETE requests deletes, everything else writes.',
      '',
      'Arguments:',
      '  method                 HTTP method: GET, POST, PUT, DELETE, PATCH, HEAD,',
      '                         OPTIONS',
      '  path                   Path relative to the REST API root, e.g.',
      '                         /process-definition/count',
      '',
      'Options:',
      '  --query <key=value>    Query parameter; repeatable',
      '  --body <json|@file|->  Request body as JSON, @path to a JSON file or - for',
      '                         stdin',
      '',
      'Global Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  --dry-run              Print the request instead of sending it',
      '  -y, --yes              Confirm delete and bulk operations',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none or basic; a username alone selects',
      '                         basic (env OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --verbose              Trace requests and responses on stderr',
      '  --out-file <path>      Write the response body to a file',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'guide',
    [
      'Usage: operate guide [options]',
      '',
      'Print the usage guide for agents and scripts as markdown: setup, workflow,',
      'conventions, output, errors and exit codes, safety and recipes.',
      '',
      'The guide is always markdown; -o/--output is accepted and ignored.',
      'skills/operate/SKILL.md of the npm package holds the same text as an agent',
      'skill.',
      '',
      'Options:',
      '  -o, --output <format>  Ignored: the guide is always markdown',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'ping',
    [
      'Usage: operate ping [options]',
      '',
      'Check the connection to the engine: REST API version, process engines and',
      'latency.',
      '',
      'Sends GET /version and GET /engine; --dry-run shows the first request.',
      '',
      'Global Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  --dry-run              Print the request instead of sending it',
      '  -y, --yes              Confirm delete and bulk operations',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none or basic; a username alone selects',
      '                         basic (env OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --verbose              Trace requests and responses on stderr',
      '  --out-file <path>      Write the response body to a file',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
];

/** The global options every operation command, `api` and `ping` list. */
const GLOBAL_OPTIONS = [
  'Global Options:',
  '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
  '                         (env OPERATE_URL)',
  '  --engine <name>        Named process engine, adds /engine/<name> to the path',
  '                         (env OPERATE_ENGINE)',
  '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
  '  --config <path>        Config file location (env OPERATE_CONFIG)',
  '  -o, --output <format>  json or table; default: table on a terminal, else json',
  '                         (env OPERATE_OUTPUT)',
  '  --fields <list>        Comma separated fields to keep, e.g.',
  '                         id,name,variables.amount; also table columns',
  '  --pretty               Indent JSON output (default on a terminal)',
  '  --dry-run              Print the request instead of sending it',
  '  -y, --yes              Confirm delete and bulk operations',
  '  --read-only            Refuse every operation that is not a read (env',
  '                         OPERATE_READ_ONLY)',
  '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
  '                         OPERATE_TIMEOUT)',
  '  -H, --header <header>  Extra request header "Name: value"; repeatable',
  '  --auth <type>          Authentication: none or basic; a username alone selects',
  '                         basic (env OPERATE_AUTH)',
  '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
  '  --auth-password-stdin  Read the Basic auth password from the first line of',
  '                         stdin (env OPERATE_PASSWORD)',
  '  --verbose              Trace requests and responses on stderr',
  '  --out-file <path>      Write the response body to a file',
  '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
  '                         verbose and config output',
  '  -h, --help             Display help for command',
];

describe('help texts', () => {
  it.each(HELP)('documents "operate %s" with its arguments and options', async (path, lines) => {
    expect(await help(path.split(' '))).toBe(`${lines.join('\n')}\n`);
  });

  it('lists the global options of operation commands with their descriptions', async () => {
    expect(await help(['task', 'claim'])).toContain(`\n\n${GLOBAL_OPTIONS.join('\n')}\n\n`);
  });

  it('lists the root options and the config command in the root help', async () => {
    const root = await help([]);
    expect(root).toMatch(/\nOptions:\n {2}-V, --version +Print the version\n/);
    expect(root).toMatch(/\n {2}config \[command\] +Manage the config file and its profiles\n/);
  });
});
