import { describe, expect, it } from 'vitest';
import { execute, fakeRuntime } from '../../../test/support/fake-runtime.js';
import { run } from '../run.js';

async function help(args: readonly string[]): Promise<string> {
  const result = await execute(run, [...args, '--help'], fakeRuntime());
  expect(result.code).toBe(0);
  return result.stdout;
}

/** The complete help of the utility commands (80 columns, not a terminal). */
const HELP: readonly (readonly [string, readonly string[]])[] = [
  [
    'config',
    [
      'Usage: operate config [options] [command]',
      '',
      'Manage the config file and its profiles. The file is written with mode 0600;',
      'values are validated before they are stored.',
      '',
      'Options:',
      '  -h, --help                 Display help for command',
      '',
      'Commands:',
      '  path                       Print the location of the config file',
      '  show                       Print the effective configuration and where each',
      '                             value comes from; header values, the password, the',
      '                             client secret and the bearer token are masked',
      '                             unless --show-secrets. -o only formats this output:',
      '                             the values are what an operation command resolves',
      '                             without it.',
      '  list                       List the profiles',
      '  set <profile>              Create or update a profile; only the given values',
      '                             change. The first profile becomes the default.',
      '                             --output is the output format stored in the',
      '                             profile; -o <format> chooses how the profile is',
      '                             printed. Basic auth: --auth basic --auth-user',
      '                             <name> --auth-password-env <VAR> keeps the password',
      '                             in an environment variable. OAuth: --auth oauth',
      '                             --oauth-issuer <url> --oauth-client-id <id>, then',
      '                             operate auth login --profile <profile> in a',
      '                             terminal. A bearer token from elsewhere: --auth',
      '                             bearer --auth-token-env <VAR>.',
      '  unset <profile> <keys...>  Remove values from a profile; auth removes all auth',
      '                             settings, an OAuth setting only itself, token (or',
      '                             tokenEnv) the bearer token',
      '  use <profile>              Make a profile the default',
      '  delete <profile>           Delete a profile',
      '  help [command]             Display help for a command',
    ],
  ],
  [
    'config path',
    [
      'Usage: operate config path [options]',
      '',
      'Print the location of the config file',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config show',
    [
      'Usage: operate config show [options]',
      '',
      'Print the effective configuration and where each value comes from; header',
      'values, the password, the client secret and the bearer token are masked unless',
      '--show-secrets. -o only formats this output: the values are what an operation',
      'command resolves without it.',
      '',
      'Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none, basic, oauth or bearer; a',
      '                         username alone selects basic, a token bearer (env',
      '                         OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --auth-token-stdin     Read the bearer token from the first line of stdin (env',
      '                         OPERATE_TOKEN)',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config list',
    [
      'Usage: operate config list [options]',
      '',
      'List the profiles',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config set',
    [
      'Usage: operate config set [options] <profile>',
      '',
      'Create or update a profile; only the given values change. The first profile',
      'becomes the default. --output is the output format stored in the profile; -o',
      '<format> chooses how the profile is printed. Basic auth: --auth basic',
      '--auth-user <name> --auth-password-env <VAR> keeps the password in an',
      'environment variable. OAuth: --auth oauth --oauth-issuer <url> --oauth-client-id',
      '<id>, then operate auth login --profile <profile> in a terminal. A bearer token',
      'from elsewhere: --auth bearer --auth-token-env <VAR>.',
      '',
      'Arguments:',
      '  profile                               Profile name, e.g. local or prod-eu',
      '',
      'Options:',
      '  --url <url>                           REST API root, e.g.',
      '                                        http://localhost:8080/engine-rest',
      '  --engine <name>                       Named process engine',
      '  --auth <type>                         Authentication: none, basic, oauth or',
      '                                        bearer',
      '  --auth-user <name>                    Username for Basic auth',
      '  --auth-password-env <VAR>             Name of the environment variable that',
      '                                        holds the Basic auth password',
      '                                        (recommended)',
      '  --auth-password-stdin                 Store the password read from the first',
      '                                        line of stdin (plain text in the file;',
      '                                        discouraged)',
      '  --oauth-issuer <url>                  OAuth issuer; the endpoints are',
      '                                        discovered from it',
      '  --oauth-authorization-endpoint <url>  Authorization endpoint (with',
      '                                        --oauth-token-endpoint, instead of',
      '                                        discovery)',
      '  --oauth-token-endpoint <url>          Token endpoint (with',
      '                                        --oauth-authorization-endpoint)',
      '  --oauth-client-id <id>                OAuth client id',
      '  --oauth-client-secret-env <VAR>       Name of the environment variable that',
      '                                        holds the client secret of a',
      '                                        confidential client',
      '  --oauth-client-secret-stdin           Store the client secret read from the',
      '                                        first line of stdin (plain text;',
      '                                        discouraged)',
      '  --oauth-scopes <scopes>               Scopes separated by spaces or commas,',
      '                                        default "openid offline_access"; \'\' for',
      '                                        none',
      '  --oauth-audience <audience>           Audience parameter of the authorization',
      '                                        request',
      '  --oauth-redirect-port <port>          Port of the login callback on 127.0.0.1,',
      '                                        default 0 (any free port)',
      '  --auth-token-env <VAR>                Name of the environment variable that',
      '                                        holds the bearer token (recommended)',
      '  --auth-token-stdin                    Store the bearer token read from the',
      '                                        first line of stdin (plain text in the',
      '                                        file; discouraged)',
      '  --output <format>                     Output format to store in the profile:',
      '                                        json or table',
      '  --timeout <ms>                        Request timeout in milliseconds',
      '  -H, --header <header>                 Header "Name: value" sent with every',
      '                                        request; repeatable',
      '  --read-only                           Refuse every operation that is not a',
      '                                        read',
      '  --no-read-only                        Allow operations that change the engine',
      '                                        state',
      '  --default                             Make this the default profile',
      '  -o <format>                           Output format of the printed profile:',
      '                                        json or table',
      '  --config <path>                       Config file location (env',
      '                                        OPERATE_CONFIG)',
      '  -h, --help                            Display help for command',
    ],
  ],
  [
    'config unset',
    [
      'Usage: operate config unset [options] <profile> <keys...>',
      '',
      'Remove values from a profile; auth removes all auth settings, an OAuth setting',
      'only itself, token (or tokenEnv) the bearer token',
      '',
      'Arguments:',
      '  profile                Profile name',
      '  keys                   Keys to remove: url, engine, auth, output, timeout,',
      '                         headers, readOnly; OAuth settings: issuer, endpoints,',
      '                         clientId, clientSecret, scopes, audience, redirectPort;',
      '                         bearer token: token, tokenEnv',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config use',
    [
      'Usage: operate config use [options] <profile>',
      '',
      'Make a profile the default',
      '',
      'Arguments:',
      '  profile                Profile name',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'config delete',
    [
      'Usage: operate config delete [options] <profile>',
      '',
      'Delete a profile',
      '',
      'Arguments:',
      '  profile                Profile name',
      '',
      'Options:',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'auth',
    [
      'Usage: operate auth [options] [command]',
      '',
      'Log in with OAuth 2.0 (authorization code flow with PKCE) and manage the cached',
      'tokens.',
      '',
      'A person runs "operate auth login" once in a terminal; every other command reads',
      'the token cache and refreshes the token on its own. Agents never log in',
      'themselves: without a usable login a command fails with LOGIN_REQUIRED (exit 4).',
      '',
      'A bearer token from elsewhere (--auth bearer, OPERATE_TOKEN) needs no login:',
      '"operate auth status" shows where it comes from and, for a JWT, its subject,',
      'issuer, audience and expiry.',
      '',
      'Options:',
      '  -h, --help      Display help for command',
      '',
      'Commands:',
      '  login           Log in with the OAuth settings of the profile: prints the',
      '                  authorization URL, opens the system browser and waits for the',
      '                  login at http://127.0.0.1:<port>/callback. Replaces a cached',
      '                  login. Meant for a person in a terminal, not for agents.',
      '  status          Show the cached OAuth login without network access: user,',
      '                  scopes and the expiry of the access and refresh token. Exit 0',
      '                  when commands can run without a new login, else LOGIN_REQUIRED',
      '                  (exit 4). With a bearer token: its source and, for a JWT,',
      '                  subject, issuer, audience and expiry; an expired JWT exits',
      '                  with TOKEN_EXPIRED (exit 4). Never prints a token.',
      '  logout          Revoke the refresh token at the authorization server (when it',
      '                  supports revocation) and remove the cached login. Works for a',
      '                  profile whose OAuth settings no longer resolve.',
      '  help [command]  Display help for a command',
    ],
  ],
  [
    'auth login',
    [
      'Usage: operate auth login [options]',
      '',
      'Log in with the OAuth settings of the profile: prints the authorization URL,',
      'opens the system browser and waits for the login at',
      'http://127.0.0.1:<port>/callback. Replaces a cached login. Meant for a person in',
      'a terminal, not for agents.',
      '',
      'Options:',
      '  --no-browser           Only print the URL; do not start the system browser',
      '  --login-timeout <ms>   How long to wait for the login, default 300000',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  --verbose              Trace requests and responses on stderr',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'auth status',
    [
      'Usage: operate auth status [options]',
      '',
      'Show the cached OAuth login without network access: user, scopes and the expiry',
      'of the access and refresh token. Exit 0 when commands can run without a new',
      'login, else LOGIN_REQUIRED (exit 4). With a bearer token: its source and, for a',
      'JWT, subject, issuer, audience and expiry; an expired JWT exits with',
      'TOKEN_EXPIRED (exit 4). Never prints a token.',
      '',
      'Options:',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --auth-token-stdin     Read the bearer token from the first line of stdin (env',
      '                         OPERATE_TOKEN)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'auth logout',
    [
      'Usage: operate auth logout [options]',
      '',
      'Revoke the refresh token at the authorization server (when it supports',
      'revocation) and remove the cached login. Works for a profile whose OAuth',
      'settings no longer resolve.',
      '',
      'Options:',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  --verbose              Trace requests and responses on stderr',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'commands',
    [
      'Usage: operate commands [group] [options]',
      '',
      'List the API groups, or the commands of a group, a search or an effect.',
      '',
      'Without arguments: every group with its number of commands, and the group',
      '"workflow" of the top-level workflow commands. With a group, --search or',
      '--effect: the matching commands with method, path, effect and summary (workflow',
      'commands first, with the operations they call). --search is case-insensitive;',
      'each of its words must occur in the command, its aliases, the operationId, the',
      'summary or the path (for workflow commands: name, summary or description).',
      '',
      'Arguments:',
      '  group                  Group whose commands to list, e.g. process-instance',
      '',
      'Options:',
      '  --search <text>        Commands whose name, alias, operationId, summary or',
      '                         path contain every word of the text',
      '  --effect <effect>      Commands with this effect (choices: "read", "write",',
      '                         "delete", "bulk")',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'describe',
    [
      'Usage: operate describe <group> [command] [options]',
      '',
      'Describe a command: usage, arguments, options, request body schema, responses',
      'and examples.',
      '',
      'Name the command by group and command (process-definition start), by its',
      'operationId (startProcessInstanceByKey) or as a workflow command (inspect). A',
      'group alone lists its commands like "operate commands <group>". Prints JSON when',
      'stdout is not a terminal, readable text otherwise.',
      '',
      'Arguments:',
      '  group                  Group (process-definition), workflow command (inspect)',
      '                         or operationId',
      '  command                Command of the group, e.g. start',
      '',
      'Options:',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'api',
    [
      'Usage: operate api <method> <path> [options]',
      '',
      'Send a raw request to a path relative to the REST API root.',
      '',
      'Adds /engine/<name> when --engine is set and the path does not start with',
      '/engine. Dot segments, repeated and trailing slashes are normalized before the',
      'request is matched and sent. The effect (for --read-only and --yes) is the one',
      'of the catalog operation with the same method and path; other GET, HEAD and',
      'OPTIONS requests are reads, DELETE requests deletes, everything else writes.',
      '',
      'Arguments:',
      '  method                 HTTP method: GET, POST, PUT, DELETE, PATCH, HEAD,',
      '                         OPTIONS',
      '  path                   Path relative to the REST API root, e.g.',
      '                         /process-definition/count',
      '',
      'Options:',
      '  --query <key=value>    Query parameter; repeatable',
      '  --body <json|@file|->  Request body as JSON, @path to a JSON file or - for',
      '                         stdin',
      '',
      'Global Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  --dry-run              Print the request instead of sending it',
      '  -y, --yes              Confirm delete and bulk operations',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none, basic, oauth or bearer; a',
      '                         username alone selects basic, a token bearer (env',
      '                         OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --auth-token-stdin     Read the bearer token from the first line of stdin (env',
      '                         OPERATE_TOKEN)',
      '  --verbose              Trace requests and responses on stderr',
      '  --out-file <path>      Write the response body to a file',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'guide',
    [
      'Usage: operate guide [options]',
      '',
      'Print the usage guide for agents and scripts as markdown: setup, workflow,',
      'conventions, output, errors and exit codes, safety and recipes.',
      '',
      'The guide is always markdown; -o/--output is accepted and ignored.',
      'skills/operate/SKILL.md of the npm package holds the same text as an agent',
      'skill.',
      '',
      'Options:',
      '  -o, --output <format>  Ignored: the guide is always markdown',
      '  -h, --help             Display help for command',
    ],
  ],
  [
    'completion',
    [
      'Usage: operate completion <bash|zsh|fish>',
      '',
      'Print the shell completion script for bash, zsh or fish. It completes commands,',
      'groups, options and their fixed values (enums, output formats, profile names,',
      'files) without contacting the engine.',
      '',
      'Install:',
      '  bash: eval "$(operate completion bash)"  in ~/.bashrc (also bash 3.2)',
      '  zsh:  mkdir -p ~/.zfunc && operate completion zsh > ~/.zfunc/_operate',
      '        and fpath=(~/.zfunc $fpath) before compinit in ~/.zshrc',
      '  fish: operate completion fish > ~/.config/fish/completions/operate.fish',
      '',
      'Arguments:',
      '  shell       Shell: bash, zsh, fish',
      '',
      'Options:',
      '  -h, --help  Display help for command',
    ],
  ],
  [
    'ping',
    [
      'Usage: operate ping [options]',
      '',
      'Check the connection to the engine: REST API version, process engines and',
      'latency.',
      '',
      'Sends GET /version and GET /engine; --dry-run shows the first request.',
      '',
      'Global Options:',
      '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
      '                         (env OPERATE_URL)',
      '  --engine <name>        Named process engine, adds /engine/<name> to the path',
      '                         (env OPERATE_ENGINE)',
      '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
      '  --config <path>        Config file location (env OPERATE_CONFIG)',
      '  -o, --output <format>  json or table; default: table on a terminal, else json',
      '                         (env OPERATE_OUTPUT)',
      '  --fields <list>        Comma separated fields to keep, e.g.',
      '                         id,name,variables.amount; also table columns',
      '  --pretty               Indent JSON output (default on a terminal)',
      '  --dry-run              Print the request instead of sending it',
      '  -y, --yes              Confirm delete and bulk operations',
      '  --read-only            Refuse every operation that is not a read (env',
      '                         OPERATE_READ_ONLY)',
      '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
      '                         OPERATE_TIMEOUT)',
      '  -H, --header <header>  Extra request header "Name: value"; repeatable',
      '  --auth <type>          Authentication: none, basic, oauth or bearer; a',
      '                         username alone selects basic, a token bearer (env',
      '                         OPERATE_AUTH)',
      '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
      '  --auth-password-stdin  Read the Basic auth password from the first line of',
      '                         stdin (env OPERATE_PASSWORD)',
      '  --auth-token-stdin     Read the bearer token from the first line of stdin (env',
      '                         OPERATE_TOKEN)',
      '  --verbose              Trace requests and responses on stderr',
      '  --out-file <path>      Write the response body to a file',
      '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
      '                         verbose and config output',
      '  -h, --help             Display help for command',
    ],
  ],
];

/** The global options every operation command, `api` and `ping` list. */
const GLOBAL_OPTIONS = [
  'Global Options:',
  '  --url <url>            REST API root, e.g. http://localhost:8080/engine-rest',
  '                         (env OPERATE_URL)',
  '  --engine <name>        Named process engine, adds /engine/<name> to the path',
  '                         (env OPERATE_ENGINE)',
  '  --profile <name>       Profile of the config file (env OPERATE_PROFILE)',
  '  --config <path>        Config file location (env OPERATE_CONFIG)',
  '  -o, --output <format>  json or table; default: table on a terminal, else json',
  '                         (env OPERATE_OUTPUT)',
  '  --fields <list>        Comma separated fields to keep, e.g.',
  '                         id,name,variables.amount; also table columns',
  '  --pretty               Indent JSON output (default on a terminal)',
  '  --dry-run              Print the request instead of sending it',
  '  -y, --yes              Confirm delete and bulk operations',
  '  --read-only            Refuse every operation that is not a read (env',
  '                         OPERATE_READ_ONLY)',
  '  --timeout <ms>         Request timeout in milliseconds, default 30000 (env',
  '                         OPERATE_TIMEOUT)',
  '  -H, --header <header>  Extra request header "Name: value"; repeatable',
  '  --auth <type>          Authentication: none, basic, oauth or bearer; a',
  '                         username alone selects basic, a token bearer (env',
  '                         OPERATE_AUTH)',
  '  --auth-user <name>     Username for Basic auth (env OPERATE_USERNAME)',
  '  --auth-password-stdin  Read the Basic auth password from the first line of',
  '                         stdin (env OPERATE_PASSWORD)',
  '  --auth-token-stdin     Read the bearer token from the first line of stdin (env',
  '                         OPERATE_TOKEN)',
  '  --verbose              Trace requests and responses on stderr',
  '  --out-file <path>      Write the response body to a file',
  '  --show-secrets         Do not mask secret headers and passwords in dry-run,',
  '                         verbose and config output',
  '  -h, --help             Display help for command',
];

describe('help texts', () => {
  it.each(HELP)('documents "operate %s" with its arguments and options', async (path, lines) => {
    expect(await help(path.split(' '))).toBe(`${lines.join('\n')}\n`);
  });

  it('lists the global options of operation commands with their descriptions', async () => {
    expect(await help(['task', 'claim'])).toContain(`\n\n${GLOBAL_OPTIONS.join('\n')}\n\n`);
  });

  it('lists the root options and the config command in the root help', async () => {
    const root = await help([]);
    expect(root).toMatch(/\nOptions:\n {2}-V, --version +Print the version\n/);
    expect(root).toMatch(/\n {2}config \[command\] +Manage the config file and its profiles\n/);
  });
});
